name: flutter_front_end
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

# Version settings for the application
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.4 # For making HTTP requests to fetch data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Uncomment and add paths here if you have assets (e.g., images) to include.
  # assets:
  #   - assets/images/

  # To include custom fonts, define them here
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
